import { SITES } from './sites.js';
const rad=Math.PI/180;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const rndSeed=seed=>()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};
const rand=rndSeed(18372);
let baseTexture;
function makeTexture(){if(baseTexture)return baseTexture;const cv=document.createElement('canvas');cv.width=1100;cv.height=1100;let ctx=cv.getContext('2d');const C=550, R=535;
  const bg=ctx.createRadialGradient(350,290,40,550,550,680);bg.addColorStop(0,'#89929b');bg.addColorStop(.34,'#5b626c');bg.addColorStop(.70,'#313941');bg.addColorStop(1,'#171f2a');ctx.fillStyle=bg;ctx.fillRect(0,0,1100,1100);
  for(let i=0;i<30000;i++){let x=rand()*1100,y=rand()*1100,r=rand()*1.8+.1; if(Math.hypot(x-C,y-C)>R)continue;ctx.fillStyle=rand()>.55?'rgba(235,243,240,.095)':'rgba(3,7,14,.16)';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
  for(let i=0;i<240;i++){let x=100+rand()*900,y=90+rand()*930,r=2+Math.pow(rand(),2.3)*64;if(Math.hypot(x-C,y-C)+r>R)continue;ctx.save();ctx.translate(x,y);ctx.scale(1,0.85+rand()*.2);const g=ctx.createRadialGradient(-r*.2,-r*.25,r*.12,0,0,r*1.22);g.addColorStop(0,'rgba(10,17,24,.62)');g.addColorStop(.65,'rgba(30,35,43,.47)');g.addColorStop(.84,'rgba(211,221,222,.23)');g.addColorStop(1,'rgba(6,10,18,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r*1.25,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(218,227,228,.12)';ctx.lineWidth=r*.13;ctx.beginPath();ctx.arc(-r*.06,-r*.07,r*.85,3.3,5.4);ctx.stroke();ctx.restore();}
  const vign=ctx.createRadialGradient(C,C,70,C,C,550);vign.addColorStop(0,'rgba(2,9,17,0)');vign.addColorStop(.85,'rgba(2,9,17,.14)');vign.addColorStop(1,'rgba(2,9,17,.95)');ctx.fillStyle=vign;ctx.fillRect(0,0,1100,1100);
  baseTexture=cv;return cv;
}
export function createMap(canvas,{onPick,onHover}){const ctx=canvas.getContext('2d');const stage=canvas.parentElement;let zoom=1;let currentSite=SITES[0];let hovered=null;let scale=1, center={x:0,y:0}, radius=0;let w=0,h=0;
  function project(lat,lon){const r=((90+lat)/9.8)*radius*zoom;return {x:center.x+r*Math.sin(lon*rad),y:center.y-r*Math.cos(lon*rad)};}
  function render(site=currentSite){currentSite=site;let dpr=Math.min(devicePixelRatio||1,2);w=stage.clientWidth;h=stage.clientHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);center={x:w*.5,y:h*.51};radius=Math.min(w*.48,h*.52);scale=dpr;
    ctx.save();ctx.beginPath();ctx.arc(center.x,center.y,radius,0,Math.PI*2);ctx.clip();ctx.drawImage(makeTexture(),center.x-radius*zoom,center.y-radius*zoom,2*radius*zoom,2*radius*zoom);
    const direction=ctx.createLinearGradient(0,0,w,h);direction.addColorStop(0,'rgba(12,23,35,.15)');direction.addColorStop(.56,'rgba(2,6,12,.07)');direction.addColorStop(1,'rgba(2,6,12,.47)');ctx.fillStyle=direction;ctx.fillRect(0,0,w,h);
    ctx.strokeStyle='rgba(206,229,237,.15)';ctx.lineWidth=1;ctx.setLineDash([3,7]);for(const lat of [-88,-86,-84,-82]){let rr=((90+lat)/9.8)*radius*zoom;ctx.beginPath();ctx.arc(center.x,center.y,rr,0,2*Math.PI);ctx.stroke();} for(let i=0;i<12;i++){let a=i*30*rad;ctx.beginPath();ctx.moveTo(center.x,center.y);ctx.lineTo(center.x+radius*Math.sin(a)*1.3,center.y-radius*Math.cos(a)*1.3);ctx.stroke();} ctx.setLineDash([]);
    ctx.font='500 10px DM Mono, monospace';ctx.fillStyle='rgba(229,240,245,.48)';[-88,-86,-84].forEach(lat=>{const p=project(lat,90);if(p.x>0&&p.x<w)ctx.fillText(`${Math.abs(lat)}°S`,p.x+6,p.y-5);});
    ctx.save();ctx.shadowColor='#8acbce';ctx.shadowBlur=10;ctx.fillStyle='#f3ead3';ctx.beginPath();ctx.arc(center.x,center.y,3.5,0,2*Math.PI);ctx.fill();ctx.restore();ctx.font='500 9px DM Mono, monospace';ctx.fillStyle='rgba(227,236,237,.70)';ctx.fillText('SOUTH POLE',center.x+11,center.y-12);
    for(let sitePoint of SITES.concat(site.custom?[site]:[])){let p=project(sitePoint.lat,sitePoint.lon),selected=sitePoint.id===site.id;if(Math.hypot(p.x-center.x,p.y-center.y)>radius+10)continue;ctx.strokeStyle=selected?'rgba(211,243,216,.58)':'rgba(227,236,243,.37)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,selected?16:9,0,Math.PI*2);ctx.stroke();ctx.fillStyle=selected?'#d6eecc':sitePoint.accent||'#d4dfe7';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=selected?16:5;ctx.beginPath();ctx.arc(p.x,p.y,selected?5:3.5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(selected){ctx.fillStyle='#f3f8f5';ctx.font='600 11px DM Sans, sans-serif';ctx.fillText(sitePoint.name.toUpperCase(),p.x+19,p.y-7);ctx.font='500 10px DM Mono, monospace';ctx.fillStyle='rgba(237,248,242,.65)';ctx.fillText(`${Math.abs(sitePoint.lat).toFixed(2)}°S`,p.x+19,p.y+9);}}
    ctx.restore();ctx.strokeStyle='rgba(171,207,224,.20)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(center.x,center.y,radius,0,Math.PI*2);ctx.stroke();
  }
  function getPoint(e){const rect=canvas.getBoundingClientRect();return {x:e.clientX-rect.left,y:e.clientY-rect.top};}
  function nearest(p){let arr=SITES.concat(currentSite.custom?[currentSite]:[]).map(site=>({site,p:project(site.lat,site.lon)})).sort((a,b)=>Math.hypot(a.p.x-p.x,a.p.y-p.y)-Math.hypot(b.p.x-p.x,b.p.y-p.y));return arr[0]&&Math.hypot(arr[0].p.x-p.x,arr[0].p.y-p.y)<22?arr[0].site:null;}
  canvas.addEventListener('pointermove',e=>{const p=getPoint(e),near=nearest(p);hovered=near;canvas.style.cursor=near||Math.hypot(p.x-center.x,p.y-center.y)<=radius?'crosshair':'default';onHover(near,e);});canvas.addEventListener('pointerleave',()=>onHover(null));
  canvas.addEventListener('click',e=>{const p=getPoint(e);if(Math.hypot(p.x-center.x,p.y-center.y)>radius)return;let site=nearest(p);if(!site){let dx=p.x-center.x,dy=center.y-p.y;let lat=-90+9.8*Math.hypot(dx,dy)/(radius*zoom);let lon=(Math.atan2(dx,dy)/rad+360)%360;site={id:'custom',name:'Custom waypoint',region:'User-selected coordinate',lat:Math.min(-80,lat),lon,tag:'Custom study',kind:'Illustrative point',accent:'#d6eecc',custom:true,detail:'Coordinates selected interactively on a schematic map. No underlying topography.'};}onPick(site);});
  if(typeof ResizeObserver!=='undefined')new ResizeObserver(()=>render()).observe(stage);else window.addEventListener('resize',()=>render());
  return {render,zoomBy(delta){zoom=clamp(Math.round((zoom+delta)*10)/10,1,2.3);render();return Math.round(zoom*100);}};
}
